export default {
    gender: [
        {gender: "any", name:"Homme", value: "male"},
        {gender: "any", name:"Femme", value: "female"}
    ],
    bodies: [
        {gender: "male", name:"Homme 1", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Business_LPR"},
        {gender: "male", name:"Homme 2", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal01_LPR"},
        {gender: "male", name:"Homme 3", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal02_LPR"},
        {gender: "male", name:"Homme 4", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal03_LPR"},
        {gender: "male", name:"Homme 5", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal04_LPR"},
        {gender: "male", name:"Homme 6", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal05_LPR"},
        {gender: "male", name:"Homme 7", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal06_LPR"},
        {gender: "male", name:"Homme 8", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal07_LPR"},
        {gender: "male", name:"Homme 9", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal08_LPR"},
        {gender: "male", name:"Homme 10", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal09_LPR"},
        {gender: "male", name:"Homme 11", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal10_LPR"},
        {gender: "male", name:"Homme 12", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal11_LPR"},
        {gender: "male", name:"Homme 13", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal12_LPR"},
        {gender: "male", name:"Homme 14", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal13_LPR"},
        {gender: "male", name:"Homme 15", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal14_LPR"},
        {gender: "male", name:"Homme 16", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal15_LPR"},
        {gender: "male", name:"Homme 17", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal16_LPR"},
        {gender: "male", name:"Homme 18", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal17_LPR"},
        {gender: "male", name:"Homme 19", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal18_LPR"},
        {gender: "male", name:"Homme 20", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal19_LPR"},
        {gender: "male", name:"Homme 21", value: "/Game/CharacterModels/SkeletalMesh/BodyMerged/HZN_CH3D_Normal20_LPR"},
        {gender: "female", name:"Femme 1", value: "/Game/CharacterModels/Female/Meshes/SK_Female01"},
        {gender: "female", name:"Femme 2", value: "/Game/CharacterModels/Female/Meshes/SK_Female02"},
        {gender: "female", name:"Femme 3", value: "/Game/CharacterModels/Female/Meshes/SK_Female03"}
    ],
    hairs: [
        {gender: "male", name:"Cheveux 1", value: "/Game/CharacterModels/SkeletalMesh/HZN_CH3D_Hair_Business_LP"},
        {gender: "male", name:"Cheveux 2", value: "/Game/CharacterModels/SkeletalMesh/HZN_CH3D_Hair_Scientist_LP"},
        {gender: "male", name:"Cheveux 3", value: "/Game/CharacterModels/SkeletalMesh/HZN_CH3D_Normal_Hair_01_LPR"},
        {gender: "male", name:"Cheveux 4", value: "/Game/CharacterModels/SkeletalMesh/HZN_CH3D_Police_Hair_LPR"},
        {gender: "male", name:"Cheveux 5", value: "/Game/CharacterModels/SkeletalMesh/HZN_CH3D_Normal_Hair_03_LPR"},
        {gender: "male", name:"Cheveux 6", value: "/Game/CharacterModels/SkeletalMesh/HZN_CH3D_Normal_Hair_02_LPR"},
        {gender: "male", name:"Cheveux 7", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair01"},
        {gender: "male", name:"Cheveux 8", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair02"},
        {gender: "male", name:"Cheveux 9", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair03"},
        {gender: "male", name:"Cheveux 10", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair04"},
        {gender: "male", name:"Cheveux 11", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair05"},
        {gender: "male", name:"Cheveux 12", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair06"},
        {gender: "male", name:"Cheveux 13", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair07"},
        {gender: "male", name:"Cheveux 14", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair08"},
        {gender: "male", name:"Cheveux 15", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair09"},
        {gender: "male", name:"Cheveux 16", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair10"},
        {gender: "male", name:"Cheveux 17", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair11"},
        {gender: "male", name:"Cheveux 18", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair12"},
        {gender: "male", name:"Cheveux 19", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair13"},
        {gender: "male", name:"Cheveux 20", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair14"},
        {gender: "male", name:"Cheveux 21", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair15"},
        {gender: "male", name:"Cheveux 22", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair16"},
        {gender: "male", name:"Cheveux 23", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair17"},
        {gender: "male", name:"Cheveux 24", value: "/Game/CharacterModels/SkeletalMesh/SK_Hair18"},
        {gender: "female", name:"Cheveux 1", value: "/Game/CharacterModels/Female/Meshes/SK_Hair01"},
        {gender: "female", name:"Cheveux 2", value: "/Game/CharacterModels/Female/Meshes/SK_Hair02"},
        {gender: "female", name:"Cheveux 3", value: "/Game/CharacterModels/Female/Meshes/SK_Hair03"}
    ],
    top: [
        {gender: "male", name:"Haut 1", value: "/Game/CharacterModels/SkeletalMesh/Outfits/HZN_Outfit_Knitted_Shirt_LPR"},
        {gender: "male", name:"Haut 3", value: "/Game/CharacterModels/SkeletalMesh/Outfits/HZN_Outfit_Piece_Shirt_LPR"},
        {gender: "male", name:"Haut 4", value: "/Game/CharacterModels/SkeletalMesh/Outfits/HZN_Outfit_Piece_TShirt_Knitted2_LPR"},
        {gender: "male", name:"Haut 5", value: "/Game/CharacterModels/SkeletalMesh/Outfits/HZN_Outfit_Piece_TShirt_Knitted_LPR"},
        {gender: "male", name:"Haut 6", value: "/Game/CharacterModels/SkeletalMesh/Outfits/HZN_Outfit_Piece_TShirt_LPR"},
        {gender: "male", name:"Haut 7", value: "/Game/CharacterModels/SkeletalMesh/Outfits/HZN_Outfit_Piece_Shirt_LPR"},
        {gender: "male", name:"Haut 8", value: "/Game/CharacterModels/Clothing/Meshes/SK_TShirt01"},
        {gender: "male", name:"Chemise 1", value: "/Game/CharacterModels/SkeletalMesh/Outfits/HZN_Outfit_Piece_FormalShirt_LPR"},
        {gender: "male", name:"Chemise 2", value: "/Game/CharacterModels/SkeletalMesh/Outfits/HZN_Outfit_Piece_FormalShirt2_LPR"},
        {gender: "male", name:"Pull Capuche", value: "/Game/CharacterModels/Clothing/Meshes/SK_Pullover"},
        {gender: "male", name:"Débardeur", value: "/Game/CharacterModels/Clothing/Meshes/SK_Undershirt01"},
        {gender: "male", name:"Débardeur et Chemise", value: "/Game/CharacterModels/Clothing/Meshes/SK_ShirtCombo01"},

        {gender: "female", name:"Haut 1", value: "/Game/CharacterModels/Female/Meshes/HZN_Outfit_Piece_FormalShirt_LPR"},
        {gender: "female", name:"Haut 4", value: "/Game/CharacterModels/Female/Meshes/SK_Pullover01"},
        {gender: "female", name:"Haut 5", value: "/Game/CharacterModels/Female/Meshes/SK_TShirt01"},
        {gender: "female", name:"Haut 6", value: "/Game/CharacterModels/Female/Meshes/SK_TShirt02"},
        {gender: "female", name:"Haut 7", value: "/Game/CharacterModels/Female/Meshes/SK_Undershirt01"}
    ],
    pants: [
        {gender: "male", name:"Pantalon 1", value: "/Game/CharacterModels/SkeletalMesh/Outfits/HZN_Outfit_Piece_CargoPants_LPR"},
        {gender: "male", name:"Pantalon 2", value: "/Game/CharacterModels/SkeletalMesh/Outfits/HZN_Outfit_Piece_DenimPants_LPR"},
        {gender: "male", name:"Pantalon 3", value: "/Game/CharacterModels/SkeletalMesh/Outfits/HZN_Outfit_Piece_FormalPants_LPR"},
        {gender: "male", name:"Pantalon 4", value: "/Game/CharacterModels/Clothing/Meshes/SK_Jeans01"},
        {gender: "male", name:"Pantalon 5", value: "/Game/CharacterModels/Clothing/Meshes/SK_Shorts01"},
        {gender: "female", name:"Pantalon 1", value: "/Game/CharacterModels/Female/Meshes/HZN_Outfit_Piece_CargoPants_LPR"},
        {gender: "female", name:"Pantalon 2", value: "/Game/CharacterModels/Female/Meshes/HZN_Outfit_Piece_DenimPants_LPR"},
        {gender: "female", name:"Pantalon 3", value: "/Game/CharacterModels/Female/Meshes/HZN_Outfit_Piece_FormalPants_LPR"},
        {gender: "female", name:"Pantalon 4", value: "/Game/CharacterModels/Female/Meshes/HZN_Outfit_Piece_Tie_LPR"},
        {gender: "female", name:"Pantalon 5", value: "/Game/CharacterModels/Female/Meshes/SK_Jeans01"},
        {gender: "female", name:"Pantalon 6", value: "/Game/CharacterModels/Female/Meshes/SK_Pants01"},
        {gender: "female", name:"Pantalon 7", value: "/Game/CharacterModels/Female/Meshes/SK_Pants02"},
        {gender: "female", name:"Pantalon 8", value: "/Game/CharacterModels/Female/Meshes/SK_Shorts01"}
    ],
    shoes: [
        {gender: "male", name:"Chaussure 1", value: "/Game/CharacterModels/SkeletalMesh/Outfits/HZN_Outfit_Piece_BusinessShoes_LPR"},
        {gender: "male", name:"Chaussure 2", value: "/Game/CharacterModels/SkeletalMesh/Outfits/HZN_Outfit_Piece_NormalShoes_LPR"},
        {gender: "male", name:"Chaussure 3", value: "/Game/CharacterModels/Clothing/Meshes/SK_Shoes01"},
        {gender: "female", name:"Chaussure 1", value: "/Game/CharacterModels/SkeletalMesh/Outfits/HZN_Outfit_Piece_BusinessShoes_LPR"},
        {gender: "female", name:"Chaussure 2", value: "/Game/CharacterModels/SkeletalMesh/Outfits/HZN_Outfit_Piece_NormalShoes_LPR"},
        {gender: "female", name:"Chaussure 3", value: "/Game/CharacterModels/Clothing/Meshes/SK_Shoes01"}
    ]
}